language: haskell

ghc:
  - 7.4.2
  - 7.6.3
  - 7.8.2

before_install:
  - cabal update
  - cabal install hpc-coveralls
  - sudo apt-get install libicu-dev

script:
  - cabal configure --enable-tests --enable-library-coverage --force-reinstalls
  - cabal build
  - run-cabal-test --show-details=always

after_script:
  - hpc-coveralls test-haskoin --exclude-dir=tests --display-report --dont-send
